apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: github-source-controller
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  source:
    git:
      revision: main
      url: https://github.com/tsalm-pivotal/tap-cartographer-workshop.git
    subPath: github-source-controller
  tag: harbor.services.demo.jg-aws.com/tap-workshop-workloads/github-source-controller