apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: TrainingPortal
metadata:
  name: scc-workshops
spec:
  portal:
    title: Workshops for Custom Supply Chain Choreographer
    ingress:
        hostname: scc-workshops
    registration:
        type: anonymous
    sessions:
      maximum: 20
    reserved: 0
    updates:
      workshop: true
  workshops:
    - expires: 300m
      name: scc-workshop
      orphaned: 40m
    - expires: 300m
      name: scc-workshop-test
      orphaned: 40m